export { default as Hero } from './Hero'
export { default as TrustIndicators } from './TrustIndicators'
export { default as Services } from './Services'
export { default as About } from './About'
export { default as WhyChooseUs } from './WhyChooseUs'
export { default as Reviews } from './Reviews'
export { default as ServiceAreas } from './ServiceAreas'
export { default as Contact } from './Contact'
